#!/bin/bash

function delete_by_re_count() {
        re_file=$2
        undel_file=$3
        file_type=$4
        echo $1 $2 $3 $4
        # 查找以 se38 开头的文件并按修改时间排序
        # -maxdepth 1 表示只查找当前目录下的文件，不递归子目录
        # -name "se38*" 匹配以 se38 开头的文件
        # -printf '%T@ %p\n' 输出文件的修改时间（Unix 时间戳）和路径
        # sort -n 按时间戳数值排序
        # cut -d' ' -f2- 提取从第二个字段开始的所有字段（去掉时间戳）

        cd "$1" || exit 1

        files=($(find . -maxdepth 1 -type "$4"  -name "$2*" -printf '%T@ %p\n' | sort -n | cut -d' ' -f2-))
#       echo ${re_file}
#       echo ${undel_file}
#       echo $1
#       echo $2

        # 计算需要删除的文件数量
        file_count=${#files[@]}
        files_to_delete=$((file_count - "$3"))

        # 如果文件数量超过了30个，则删除多余的文件
        if [ "$files_to_delete" -gt 0 ]; then
            for ((i=0; i<files_to_delete; i++)); do
                file_to_delete="${files[$i]}"
                rm -rf "$file_to_delete"
                echo "删除文件: $file_to_delete"
            done
        else
            echo "没有需要删除的文件，当前文件数量为: $file_count"
        fi
}

function delete_files_by_re_count() {
        delete_by_re_count $1 $2 $3 f
}

function delete_dirs_by_re_count() {
        delete_by_re_count $1 $2 $3 d
}

fileCount=30

delete_files_by_re_count "/nfs/mysql/" "all_38" ${fileCount}
delete_files_by_re_count "/nfs/mysql/" "all_58" ${fileCount}
delete_files_by_re_count "/nfs/mysql/" "all_202" ${fileCount}
delete_files_by_re_count "/nfs/mysql/" "pricing_param_202" ${fileCount}
delete_files_by_re_count "/nfs/mysql/" "pricing_param_38" ${fileCount}
delete_files_by_re_count "/nfs/mysql/" "pricing_param_cd5j" ${fileCount}

delete_dirs_by_re_count "/nfs/mongodb/" "202" ${fileCount}
delete_dirs_by_re_count "/nfs/mongodb/" "38_" ${fileCount}
delete_dirs_by_re_count "/nfs/mongodb/" "58_" ${fileCount}
