services:
  seata-server:
    container_name: seata
    restart: unless-stopped
    image: seataio/seata-server:1.7.0
    ports:
      - 8091:8091
    environment:
      TZ: Asia/Shanghai
      SEATA_PORT: '8091'
      STORE_MODE: file
